---
version: '3'
services:
  web:
    ports:
    - '4567'
    command: ruby app.rb
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
    - sinatra-gems:/home/docker/.gem/ruby/
    - ".:/usr/src/app"
    environment:
      HOST: http://sinatra.docker
      VIRTUAL_HOST: sinatra.docker
      VIRTUAL_PORT: 4567
volumes:
  sinatra-gems:
    driver: local
